"""
agents/orchestrator.py
Orchestrator — coordinates the full ClinicalBridge multi-agent pipeline.

Workflow:
  1. Validate incoming RPM alert
  2. Run Triage Agent
  3. If Critical: escalate immediately (bypass synthesis)
  4. Else: run EHR and Anamnesis agents in PARALLEL (asyncio)
  5. Run Synthesis Agent
  6. Validate CCB and return

Implements:
  - Parallel agent dispatch with asyncio
  - Safety escalation pathway (Critical bypass)
  - Fallback handling for agent failures
  - Session audit logging
  - Schema validation on CCB output
"""

import asyncio
import json
import time
from datetime import datetime
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeoutError

from agents.triage_agent    import TriageAgent
from agents.ehr_retrieval_agent import EHRRetrievalAgent
from agents.anamnesis_agent import AnamnesisAgent
from agents.synthesis_agent import SynthesisAgent


# ── Configuration ─────────────────────────────────────────────────────────────
AGENT_TIMEOUT_SECONDS = 30    # Per-agent timeout
LOG_DIR               = Path("logs")
LOG_DIR.mkdir(exist_ok=True)


# ── Critical escalation notice ────────────────────────────────────────────────

CRITICAL_ESCALATION_TEMPLATE = {
    "escalation_type":  "CRITICAL_ALERT",
    "message":          "This alert has been classified as CRITICAL and requires immediate human clinical review. The full synthesis pipeline has been bypassed to minimise delay.",
    "immediate_action": "Contact the patient or their care team immediately. Do not wait for full synthesis.",
    "disclaimer":       "This Clinical Context Brief is a decision-support summary generated by an AI prototype using simulated data. It does not constitute a diagnosis or treatment order. All clinical decisions require review and approval by a qualified physician.",
}


# ── Orchestrator ──────────────────────────────────────────────────────────────

class Orchestrator:
    """
    Coordinates the full ClinicalBridge multi-agent pipeline.
    """

    def __init__(self):
        self.triage_agent    = TriageAgent()
        self.ehr_agent       = EHRRetrievalAgent()
        self.anamnesis_agent = AnamnesisAgent()
        self.synthesis_agent = SynthesisAgent()
        self.session_log: list[dict] = []

    # ── Logging ──────────────────────────────────────────────────────────────

    def _log(self, event: str, data: dict) -> None:
        """Append an event to the session log."""
        entry = {
            "timestamp": datetime.utcnow().isoformat(),
            "event":     event,
            "data":      data,
        }
        self.session_log.append(entry)

    def _save_session_log(self, patient_id: str) -> Path:
        """Save the session log to disk for auditability."""
        ts       = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        log_path = LOG_DIR / f"session_{patient_id}_{ts}.json"
        with open(log_path, "w") as f:
            json.dump(self.session_log, f, indent=2)
        return log_path

    # ── Input validation ──────────────────────────────────────────────────────

    def _validate_alert(self, alert: dict) -> None:
        """Validate that the RPM alert has all required fields."""
        required = ["patient_id", "timestamp", "device_type", "measurement_type",
                    "value", "unit", "baseline", "alert_threshold", "alert_category"]
        missing = [f for f in required if f not in alert]
        if missing:
            raise ValueError(f"RPM alert missing required fields: {missing}")

    # ── Parallel retrieval ────────────────────────────────────────────────────

    def _run_ehr_retrieval(self, patient_id: str, triage_output: dict) -> dict:
        """Run EHR retrieval — designed to be called in a thread."""
        try:
            return self.ehr_agent.run(patient_id, triage_output)
        except Exception as e:
            self._log("EHR_RETRIEVAL_ERROR", {"error": str(e)})
            return {
                "patient_id":         patient_id,
                "relevant_diagnoses": [],
                "relevant_medications": [],
                "relevant_labs":      [],
                "relevant_visit_notes": [],
                "allergy_alerts":     [],
                "pattern_flags":      [],
                "retrieval_confidence": 0.0,
                "missing_data_flags": [f"EHR RETRIEVAL FAILED — {str(e)}", "LOW EHR CONFIDENCE — synthesis will rely heavily on anamnesis data"],
                "source_references":  [],
                "_meta":              {"agent": "EHRRetrievalAgent", "error": str(e)},
            }

    def _run_anamnesis(self, patient_id: str, triage_output: dict) -> dict:
        """Run anamnesis retrieval — designed to be called in a thread."""
        try:
            return self.anamnesis_agent.run(patient_id, triage_output)
        except Exception as e:
            self._log("ANAMNESIS_ERROR", {"error": str(e)})
            return {
                "patient_id":         patient_id,
                "reporter_type":      "unknown",
                "medication_adherence_summary": f"Anamnesis retrieval failed: {str(e)}",
                "medications_taken_as_prescribed": [],
                "medications_stopped_by_patient": [],
                "otc_medications":    [],
                "recent_symptoms":    "Anamnesis data unavailable.",
                "symptom_timeline":   [],
                "lifestyle_factors":  "Unknown.",
                "family_history_highlights": "Unknown.",
                "patient_concerns":   "Unknown.",
                "adherence_confidence": "Unknown",
                "sensitivity_flags":  ["ANAMNESIS_RETRIEVAL_FAILED"],
                "source":             f"anamnesis_record_{patient_id}",
                "_meta":              {"agent": "AnamnesisAgent", "error": str(e)},
            }

    # ── Main pipeline ─────────────────────────────────────────────────────────

    def run(self, alert: dict) -> dict:
        """
        Run the full ClinicalBridge pipeline for an RPM alert.

        Args:
            alert: RPM alert dict

        Returns:
            Clinical Context Brief (CCB) dict, or critical escalation notice
        """
        pipeline_start = time.time()
        patient_id     = alert.get("patient_id", "UNKNOWN")

        self._log("PIPELINE_START", {"patient_id": patient_id, "alert": alert})

        # ── Step 1: Validate input ────────────────────────────────────────────
        try:
            self._validate_alert(alert)
        except ValueError as e:
            self._log("VALIDATION_ERROR", {"error": str(e)})
            raise

        # ── Step 2: Triage Agent ──────────────────────────────────────────────
        print(f"[1/4] Running Triage Agent for patient {patient_id}...")
        triage_start  = time.time()
        triage_output = self.triage_agent.run(alert)
        triage_time   = time.time() - triage_start

        self._log("TRIAGE_COMPLETE", {
            "urgency":             triage_output.get("urgency"),
            "escalate_immediately": triage_output.get("escalate_immediately"),
            "latency_s":           round(triage_time, 2),
        })
        print(f"    → Urgency: {triage_output.get('urgency')} ({triage_time:.1f}s)")

        # ── Step 3: Critical escalation check ────────────────────────────────
        if triage_output.get("escalate_immediately"):
            escalation_notice = {
                **CRITICAL_ESCALATION_TEMPLATE,
                "patient_id":       patient_id,
                "generated_at":     datetime.utcnow().isoformat(),
                "triage_output":    triage_output,
                "total_latency_s":  round(time.time() - pipeline_start, 2),
            }
            self._log("CRITICAL_ESCALATION", {"patient_id": patient_id})
            log_path = self._save_session_log(patient_id)
            escalation_notice["session_log"] = str(log_path)
            print(f"    ⚠️  CRITICAL alert — escalating immediately. Synthesis bypassed.")
            return escalation_notice

        # ── Step 4: Parallel retrieval ────────────────────────────────────────
        print(f"[2/4] Running EHR + Anamnesis agents in parallel...")
        retrieval_start = time.time()

        with ThreadPoolExecutor(max_workers=2) as executor:
            ehr_future       = executor.submit(self._run_ehr_retrieval, patient_id, triage_output)
            anamnesis_future = executor.submit(self._run_anamnesis,     patient_id, triage_output)

            try:
                ehr_context = ehr_future.result(timeout=AGENT_TIMEOUT_SECONDS)
            except FuturesTimeoutError:
                self._log("EHR_TIMEOUT", {"timeout_s": AGENT_TIMEOUT_SECONDS})
                ehr_context = self._run_ehr_retrieval.__func__(
                    self, patient_id, triage_output  # fallback with error output
                )
                ehr_context["missing_data_flags"].append("EHR RETRIEVAL TIMED OUT")

            try:
                anamnesis_summary = anamnesis_future.result(timeout=AGENT_TIMEOUT_SECONDS)
            except FuturesTimeoutError:
                self._log("ANAMNESIS_TIMEOUT", {"timeout_s": AGENT_TIMEOUT_SECONDS})
                anamnesis_summary = self._run_anamnesis.__func__(
                    self, patient_id, triage_output  # fallback with error output
                )
                anamnesis_summary["sensitivity_flags"].append("ANAMNESIS_TIMED_OUT")

        retrieval_time = time.time() - retrieval_start
        self._log("RETRIEVAL_COMPLETE", {
            "ehr_confidence":      ehr_context.get("retrieval_confidence"),
            "anamnesis_confidence": anamnesis_summary.get("adherence_confidence"),
            "latency_s":           round(retrieval_time, 2),
        })
        print(f"    → EHR confidence: {ehr_context.get('retrieval_confidence')} | "
              f"Anamnesis confidence: {anamnesis_summary.get('adherence_confidence')} "
              f"({retrieval_time:.1f}s)")

        # ── Step 5: Synthesis Agent ───────────────────────────────────────────
        print(f"[3/4] Running Synthesis Agent...")
        synthesis_start = time.time()
        ccb             = self.synthesis_agent.run(alert, triage_output, ehr_context, anamnesis_summary)
        synthesis_time  = time.time() - synthesis_start

        self._log("SYNTHESIS_COMPLETE", {
            "confidence_score": ccb.get("confidence_score"),
            "urgency":          ccb.get("alert_summary", {}).get("urgency_classification"),
            "latency_s":        round(synthesis_time, 2),
        })
        print(f"    → CCB generated. Confidence: {ccb.get('confidence_score')} ({synthesis_time:.1f}s)")

        # ── Step 6: Validate output ───────────────────────────────────────────
        required_ccb_fields = ["patient_id", "alert_summary", "patient_snapshot",
                               "contextual_analysis", "recommended_actions", "disclaimer"]
        missing_fields = [f for f in required_ccb_fields if f not in ccb]
        if missing_fields:
            self._log("CCB_VALIDATION_WARNING", {"missing_fields": missing_fields})
            print(f"    ⚠️  CCB missing fields: {missing_fields}")

        # ── Step 7: Finalise ──────────────────────────────────────────────────
        total_time = time.time() - pipeline_start
        ccb["_pipeline_meta"] = {
            "total_latency_s":    round(total_time, 2),
            "triage_latency_s":   round(triage_time, 2),
            "retrieval_latency_s": round(retrieval_time, 2),
            "synthesis_latency_s": round(synthesis_time, 2),
        }

        log_path = self._save_session_log(patient_id)
        ccb["_session_log"] = str(log_path)

        print(f"[4/4] Pipeline complete. Total time: {total_time:.1f}s")
        return ccb


# ── Convenience function ──────────────────────────────────────────────────────

def run_pipeline(alert: dict) -> dict:
    """Run the full ClinicalBridge pipeline for an RPM alert."""
    orchestrator = Orchestrator()
    return orchestrator.run(alert)
